### ISSUE TITLE
图像模糊问题

### ISSUE THREAD

**Issue by deism** [Eastzonetech/GOLDEN_DF_PE_VP#1]
可能的原因是前校正参数不准确造成图像边缘模糊

**Comment by teamsoftware123** [comment]
导致图像模糊只要还是由于vp增强参数设置的问题，本次参数记录如下：
增强 0
均衡 0.3
范围压缩 0
降噪 0
均衡幅度 500
均衡细节 512
递归0.8
前降噪 0
后降噪 1
前增强 0
后增强 0
前校准 0.7
后校准 0
